name: "Package Publisher"

on:
  push:
    branches:
      - develop
      - 'feature/**'

jobs:

#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 12
#      - run: yarn install --frozen-lockfile
#      - run: yarn build

  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@amoncusir'

      - name: 'yarn install'
        run: yarn install --frozen-lockfile

      - name: 'yarn build'
        run: yarn build

      - name: 'yarn publish'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn publish --new-version ${GITHUB_REF##*/}
