name: "Package Publisher"

on:
  push:
    branches:
      - develop
      - 'feature/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: yarn build

  publish:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com/'
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: yarn install --frozen-lockfile && yarn build
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com/'
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn publish --preid ${GITHUB_REF##*/}
#      - run: npm publish --tag "${GITHUB_REF##*/}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
