name: "Package Publisher"

on:
  release:
    types:
      - created

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@amoncusir'

      - name: 'Install'
        run: npm ci

      - name: 'Build'
        run: npm build

      - name: 'Publish'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: 'npm publish'
